### ISSUE TITLE
What if I want to manipulate your code for changing product's price? Getters are there, but there is no way to change or set the price of a product other than using the constructor method

### ISSUE THREAD

**Issue by SkrytnayaRediska** [NikitaZhukovsky/oop-tasks-part-2#1]
https://github.com/NikitaZhukovsky/oop-tasks-part-2/blob/303f0e9022540210b163be9dbe2fc059efa1839d/Task_1/products.py#L1-L14

**Comment by NikitaZhukovsky** [comment]
Add a method with the price.setter decorator, now the price can be changed in this way "product_one.price(....)"
