### ISSUE TITLE
How should the user understand what to input? (hypothetical user can not see your code)

### ISSUE THREAD

**Issue by SkrytnayaRediska** [NikitaZhukovsky/oop-tasks-part-2#6]
https://github.com/NikitaZhukovsky/oop-tasks-part-2/blob/303f0e9022540210b163be9dbe2fc059efa1839d/Task_2/bee_elephant.py#L41-L46
![Снимок экрана 2024-01-24 в 16 59 05](https://github.com/NikitaZhukovsky/oop-tasks-part-2/assets/44698380/6ccd00b7-4b47-45a4-82cf-56001e63d8d8)

**Comment by NikitaZhukovsky** [comment]
Fixed it
