### ISSUE TITLE
Checks for this case

### ISSUE THREAD

**Issue by SkrytnayaRediska** [NikitaZhukovsky/oop-tasks-part-2#7]
https://github.com/NikitaZhukovsky/oop-tasks-part-2/blob/303f0e9022540210b163be9dbe2fc059efa1839d/Task_3/bus.py#L64
![Снимок экрана 2024-01-24 в 17 03 31](https://github.com/NikitaZhukovsky/oop-tasks-part-2/assets/44698380/7c3e9733-ab61-49b9-87c5-46267cef0c34)

**Comment by NikitaZhukovsky** [comment]
Fixed it
