### ISSUE TITLE
Strange behavior

### ISSUE THREAD

**Issue by SkrytnayaRediska** [NikitaZhukovsky/oop-tasks-part-2#8]
https://github.com/NikitaZhukovsky/oop-tasks-part-2/blob/303f0e9022540210b163be9dbe2fc059efa1839d/Task_3/bus.py#L64
![Снимок экрана 2024-01-24 в 17 05 52](https://github.com/NikitaZhukovsky/oop-tasks-part-2/assets/44698380/d3bd6b86-fd6b-4f52-8596-9eb28ab05616)

**Comment by NikitaZhukovsky** [comment]
Fixed it
